In [1]:
def times2(num):
    return num ** 2



In [3]:
times2(23)

529

In [5]:
seq = [1, 2, 3, 4]

In [ ]:
# map()

In [7]:
list(map(times2, seq))

[1, 4, 9, 16]

In [8]:
list(map(lambda num: num ** 2, seq ))

[1, 4, 9, 16]

In [9]:
seq = (1, 2, 3, 4)

In [10]:
list(map(lambda num: num ** 2, seq))

[1, 4, 9, 16]

In [11]:
lst = [1, 2, 3]


In [12]:
list = [num * 2 for num in lst ]

In [13]:
list

[2, 4, 6]

In [14]:
lst = [1, 2, 3, 4, 5, 6, 7, 8]

In [23]:
list(filter(lambda num: num%2 == 0, lst))

TypeError: 'list' object is not callable

In [25]:
import numpy as np

In [50]:
np.random.randint(1,7)

1

In [51]:
arr = np.arange(0,11)

In [52]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
arr[8:8]

array([], dtype=int64)

In [60]:
arr.dtype

dtype('int64')

In [61]:
arr[0:5] = 200


In [62]:
arr

array([200, 200, 200, 200, 200,   5,   6,   7,   8,   9,  10])

In [63]:
arr = np.arange(0,11)

In [64]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])